version: '3.3'

services:
  mysql-product:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data_product:/var/lib/mysql

  phpmyadmin-product:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=${PMA_HOST}
    ports:
      - "8080:80"

  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_DIALECT=${DB_DIALECT}
    depends_on:
      - mysql-product



 